DROP DATABASE IF EXISTS "task-tracker";

DROP ROLE IF EXISTS user12;
CREATE ROLE user12 WITH
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  NOREPLICATION
  CONNECTION LIMIT 5
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:HjPmjIoh65HHakDRcnRHdw==$+OrPclhiE7nGyEZ4Z6kdG7OuBGRbqib4egY2yZ4mHCA=:p9ZxYkdw5LM/ar6ma9uxkSGtWY3ume0DUY0U/dMoXy0=';

CREATE DATABASE "task-tracker"
    WITH
    OWNER = user12
    ENCODING = 'UTF8'
    LC_COLLATE = 'English_United States.1251'
    LC_CTYPE = 'English_United States.1251'
    TABLESPACE = pg_default
    CONNECTION LIMIT = 20;

